export interface DirectoryMember {
  id: string
  name: string
  role: string
  image?: string
  bio: string
  specializations: string[]
  email?: string
  phone?: string
  location?: string
  website?: string
  experience: string
  equipment?: string[]
  rates?: string
  availability: string
  portfolio?: string[]
  certifications?: string[]
}

export const directoryMembers: DirectoryMember[] = [
  {
    id: "helper-1",
    name: "Rajesh Kumar",
    role: "Cinematographer",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Professional cinematographer with 12 years of experience in feature films and commercials. Specializes in dramatic lighting and handheld camera work.",
    specializations: ["Feature Films", "Commercials", "Music Videos"],
    email: "rajesh.cinematographer@gmail.com",
    phone: "+91 98765 43210",
    location: "Mumbai, Maharashtra",
    website: "www.rajeshcinematography.com",
    experience: "12 years",
    equipment: ["RED Camera", "Arri Alexa", "Steadicam", "Drone"],
    rates: "₹25,000 - ₹50,000 per day",
    availability: "Available",
    portfolio: ["Bollywood Feature Film 2023", "Samsung Commercial", "Music Video - Popular Artist"],
    certifications: ["Certified Drone Pilot", "Arri Camera Certified"],
  },
  {
    id: "helper-2",
    name: "Priya Sharma",
    role: "Choreographer",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Award-winning choreographer specializing in Bollywood dance sequences and contemporary movements. Has worked on 50+ films and music videos.",
    specializations: ["Bollywood Dance", "Contemporary", "Folk Dance"],
    email: "priya.choreographer@gmail.com",
    phone: "+91 98765 43211",
    location: "Mumbai, Maharashtra",
    website: "www.priyachoreography.com",
    experience: "8 years",
    equipment: ["Dance Studio", "Sound System", "Mirrors"],
    rates: "₹15,000 - ₹30,000 per day",
    availability: "Available",
    portfolio: ["Major Bollywood Film 2023", "International Music Video", "Dance Reality Show"],
    certifications: ["Certified Dance Instructor", "Bollywood Dance Academy Graduate"],
  },
  {
    id: "helper-3",
    name: "Arjun Mehta",
    role: "Music Composer",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Versatile music composer creating original scores for films, web series, and commercials. Expert in both traditional and modern music production.",
    specializations: ["Film Scores", "Background Music", "Jingles"],
    email: "arjun.composer@gmail.com",
    phone: "+91 98765 43212",
    location: "Chennai, Tamil Nadu",
    website: "www.arjunmusic.com",
    experience: "10 years",
    equipment: ["Professional Studio", "Digital Audio Workstation", "Live Orchestra"],
    rates: "₹50,000 - ₹2,00,000 per project",
    availability: "Busy until March 2024",
    portfolio: ["Award-winning Film Score 2023", "Popular Web Series Theme", "National Commercial Jingle"],
    certifications: ["Music Production Certified", "Sound Engineering Diploma"],
  },
  {
    id: "helper-4",
    name: "Kavya Patel",
    role: "Event Organizer",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Professional event organizer specializing in film premieres, award ceremonies, and industry networking events. Known for flawless execution.",
    specializations: ["Film Premieres", "Award Ceremonies", "Corporate Events"],
    email: "kavya.events@gmail.com",
    phone: "+91 98765 43213",
    location: "Delhi, India",
    website: "www.kavyaevents.com",
    experience: "6 years",
    equipment: ["Event Planning Team", "Vendor Network", "Technical Support"],
    rates: "₹1,00,000 - ₹10,00,000 per event",
    availability: "Available",
    portfolio: ["Filmfare Awards 2023", "Major Film Premiere", "Industry Networking Event"],
    certifications: ["Certified Event Planner", "Project Management Professional"],
  },
  {
    id: "helper-5",
    name: "Vikram Singh",
    role: "Sound Engineer",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Expert sound engineer with specialization in location recording and post-production mixing. Ensures crystal clear audio for all productions.",
    specializations: ["Location Recording", "Post-Production", "Live Sound"],
    email: "vikram.sound@gmail.com",
    phone: "+91 98765 43214",
    location: "Pune, Maharashtra",
    website: "www.vikramsound.com",
    experience: "9 years",
    equipment: ["Professional Microphones", "Mixing Console", "Recording Equipment"],
    rates: "₹20,000 - ₹40,000 per day",
    availability: "Available",
    portfolio: ["Feature Film Sound Design", "Documentary Recording", "Live Concert Recording"],
    certifications: ["Pro Tools Certified", "Audio Engineering Diploma"],
  },
  {
    id: "helper-6",
    name: "Anita Desai",
    role: "Makeup Artist",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Professional makeup artist specializing in character makeup, special effects, and beauty makeup for films and television productions.",
    specializations: ["Character Makeup", "Special Effects", "Beauty Makeup"],
    email: "anita.makeup@gmail.com",
    phone: "+91 98765 43215",
    location: "Bangalore, Karnataka",
    website: "www.anitamakeup.com",
    experience: "7 years",
    equipment: ["Professional Makeup Kit", "Special Effects Materials", "Airbrush System"],
    rates: "₹10,000 - ₹25,000 per day",
    availability: "Available",
    portfolio: ["Period Drama Makeup", "Horror Film Special Effects", "Celebrity Photoshoot"],
    certifications: ["Professional Makeup Artist Certified", "Special Effects Makeup Course"],
  },
  {
    id: "helper-7",
    name: "Rohit Kapoor",
    role: "Camera House Owner",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Owner of premium camera rental house providing latest equipment for film productions. Complete camera packages with technical support.",
    specializations: ["Camera Rental", "Equipment Support", "Technical Consultation"],
    email: "rohit.cameras@gmail.com",
    phone: "+91 98765 43216",
    location: "Mumbai, Maharashtra",
    website: "www.rohitcameras.com",
    experience: "15 years",
    equipment: ["RED Cameras", "Arri Alexa", "Lenses", "Accessories"],
    rates: "₹15,000 - ₹1,00,000 per day",
    availability: "Available",
    portfolio: ["Major Bollywood Productions", "International Commercials", "Web Series"],
    certifications: ["Authorized Equipment Dealer", "Technical Support Certified"],
  },
  {
    id: "helper-8",
    name: "Deepika Rao",
    role: "Costume Designer",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Creative costume designer with expertise in period costumes, contemporary fashion, and character-specific designs for films and theater.",
    specializations: ["Period Costumes", "Contemporary Fashion", "Character Design"],
    email: "deepika.costumes@gmail.com",
    phone: "+91 98765 43217",
    location: "Hyderabad, Telangana",
    website: "www.deepikacostumes.com",
    experience: "8 years",
    equipment: ["Costume Workshop", "Fabric Collection", "Tailoring Team"],
    rates: "₹20,000 - ₹50,000 per project",
    availability: "Available",
    portfolio: ["Historical Drama Costumes", "Modern Film Wardrobe", "Theater Production"],
    certifications: ["Fashion Design Graduate", "Costume Design Specialist"],
  },
  {
    id: "helper-9",
    name: "Sameer Ahmed",
    role: "Lighting Technician",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Expert lighting technician with extensive knowledge of film lighting setups, LED systems, and creative lighting solutions for various productions.",
    specializations: ["Film Lighting", "LED Systems", "Creative Lighting"],
    email: "sameer.lighting@gmail.com",
    phone: "+91 98765 43218",
    location: "Kolkata, West Bengal",
    website: "www.sameerlighting.com",
    experience: "11 years",
    equipment: ["LED Panels", "Traditional Lights", "Grip Equipment"],
    rates: "₹18,000 - ₹35,000 per day",
    availability: "Available",
    portfolio: ["Feature Film Lighting", "Commercial Lighting", "Music Video Setup"],
    certifications: ["Lighting Technician Certified", "Electrical Safety Trained"],
  },
  {
    id: "helper-10",
    name: "Meera Joshi",
    role: "Script Supervisor",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Meticulous script supervisor ensuring continuity and accuracy during film productions. Expert in maintaining detailed shooting logs and continuity reports.",
    specializations: ["Script Continuity", "Shooting Logs", "Production Reports"],
    email: "meera.script@gmail.com",
    phone: "+91 98765 43219",
    location: "Jaipur, Rajasthan",
    website: "www.meerascript.com",
    experience: "5 years",
    equipment: ["Digital Script Software", "Continuity Camera", "Production Tools"],
    rates: "₹12,000 - ₹20,000 per day",
    availability: "Available",
    portfolio: ["Major Film Productions", "Web Series", "Documentary Projects"],
    certifications: ["Script Supervision Course", "Production Management Certified"],
  },
  {
    id: "helper-11",
    name: "Karan Malhotra",
    role: "Stunt Coordinator",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Professional stunt coordinator with expertise in action sequences, fight choreography, and safety protocols for film and television productions.",
    specializations: ["Action Sequences", "Fight Choreography", "Safety Protocols"],
    email: "karan.stunts@gmail.com",
    phone: "+91 98765 43220",
    location: "Mumbai, Maharashtra",
    website: "www.karanstunts.com",
    experience: "13 years",
    equipment: ["Safety Equipment", "Stunt Props", "Trained Stunt Team"],
    rates: "₹30,000 - ₹75,000 per day",
    availability: "Available",
    portfolio: ["Action Film Sequences", "TV Serial Stunts", "Commercial Action"],
    certifications: ["Stunt Safety Certified", "Fight Choreography Trained"],
  },
  {
    id: "helper-12",
    name: "Ritu Sharma",
    role: "Production Designer",
    image: "/placeholder.svg?height=100&width=100",
    bio: "Creative production designer specializing in set design, location scouting, and visual aesthetics for films, commercials, and web series.",
    specializations: ["Set Design", "Location Scouting", "Visual Aesthetics"],
    email: "ritu.production@gmail.com",
    phone: "+91 98765 43221",
    location: "Mumbai, Maharashtra",
    website: "www.rituproduction.com",
    experience: "9 years",
    equipment: ["Design Software", "Art Department Team", "Props Collection"],
    rates: "₹25,000 - ₹60,000 per project",
    availability: "Available",
    portfolio: ["Period Film Sets", "Modern Commercial Sets", "Web Series Design"],
    certifications: ["Production Design Graduate", "Art Direction Certified"],
  },
]

export function getDirectoryMembers(): DirectoryMember[] {
  return directoryMembers
}

export function getUniqueRoles(): string[] {
  const roles = directoryMembers.map((member) => member.role)
  return Array.from(new Set(roles)).sort()
}
