import type { Event } from "@/lib/types"

// Extended event data with additional details for modals
export const eventsData: Event[] = [
  {
    id: "1",
    title: "Annual Film Awards Ceremony",
    description:
      "Join us for our prestigious annual awards ceremony celebrating the best in filmmaking. This glamorous evening will honor outstanding achievements in directing, cinematography, and storytelling.",
    image: "/film-awards-ceremony.png",
    date: "2024-03-15",
    time: "7:00 PM - 11:00 PM",
    location: "Grand Theater, Downtown",
    type: "Awards",
    tags: ["Awards", "Formal", "Networking"],
    attendees: 250,
    organizer: "Directors Guild Board",
    venue: "Grand Theater",
    venueAddress: "123 Main Street, Downtown, City 12345",
    ticketPrice: "$75",
    dresscode: "Black Tie",
    agenda: [
      "7:00 PM - Red Carpet & Reception",
      "8:00 PM - Awards Ceremony Begins",
      "10:00 PM - After Party & Networking",
      "11:00 PM - Event Concludes",
    ],
    speakers: ["John Director", "Sarah Filmmaker", "Mike Producer"],
    requirements: "RSVP required by March 10th",
    contact: "events@directorsguild.org",
  },
  {
    id: "2",
    title: "Summer Workshop Series: Advanced Cinematography",
    description:
      "Intensive 3-day workshop covering advanced cinematography techniques, lighting setups, and camera movement. Learn from industry professionals and hands-on practice.",
    image: "/film-workshop.png",
    date: "2024-06-20",
    time: "9:00 AM - 5:00 PM",
    location: "Film Studio Complex",
    type: "Workshop",
    tags: ["Education", "Hands-on", "Cinematography"],
    attendees: 30,
    organizer: "Education Committee",
    venue: "Film Studio Complex",
    venueAddress: "456 Studio Drive, Film District, City 12345",
    ticketPrice: "$299 (3-day pass)",
    dresscode: "Casual/Comfortable",
    agenda: [
      "Day 1: Camera Fundamentals & Composition",
      "Day 2: Lighting Techniques & Color Theory",
      "Day 3: Movement & Advanced Techniques",
    ],
    speakers: ["Alex Cinematographer", "Lisa Lighting Expert", "Tom Camera Operator"],
    requirements: "Basic camera knowledge recommended",
    contact: "workshops@directorsguild.org",
  },
  {
    id: "3",
    title: "New Directors Showcase",
    description:
      "Platform for emerging directors to showcase their latest works. Network with industry professionals and get feedback on your projects.",
    image: "/young-filmmakers-presentation.png",
    date: "2024-04-10",
    time: "6:00 PM - 10:00 PM",
    location: "Community Arts Center",
    type: "Showcase",
    tags: ["Emerging", "Networking", "Screening"],
    attendees: 120,
    organizer: "New Talent Committee",
    venue: "Community Arts Center",
    venueAddress: "789 Arts Boulevard, Creative Quarter, City 12345",
    ticketPrice: "Free for members, $15 for guests",
    dresscode: "Smart Casual",
    agenda: [
      "6:00 PM - Registration & Welcome Drinks",
      "6:30 PM - Film Screenings Begin",
      "8:30 PM - Q&A with Directors",
      "9:00 PM - Networking Reception",
    ],
    speakers: ["Featured New Directors", "Industry Mentors"],
    requirements: "Submission deadline: March 25th",
    contact: "showcase@directorsguild.org",
  },
  {
    id: "4",
    title: "Behind the Scenes: Documentary Filmmaking",
    description:
      "Exclusive behind-the-scenes look at documentary production. Learn about research, interviewing techniques, and post-production workflows.",
    image: "/night-shoot.png",
    date: "2024-05-05",
    time: "2:00 PM - 6:00 PM",
    location: "Documentary Center",
    type: "Educational",
    tags: ["Documentary", "Behind-the-scenes", "Production"],
    attendees: 80,
    organizer: "Documentary Division",
    venue: "Documentary Center",
    venueAddress: "321 Media Street, Arts District, City 12345",
    ticketPrice: "$45",
    dresscode: "Casual",
    agenda: [
      "2:00 PM - Welcome & Introduction",
      "2:30 PM - Pre-production Planning",
      "3:30 PM - Filming Techniques",
      "4:30 PM - Post-production Workflow",
      "5:30 PM - Q&A Session",
    ],
    speakers: ["Documentary Filmmaker Jane Smith", "Editor Bob Wilson"],
    requirements: "Interest in documentary filmmaking",
    contact: "documentary@directorsguild.org",
  },
  {
    id: "5",
    title: "Networking Night: Industry Connections",
    description:
      "Monthly networking event for directors, producers, and industry professionals. Build connections and explore collaboration opportunities.",
    image: "/film-networking-event.png",
    date: "2024-07-12",
    time: "7:00 PM - 10:00 PM",
    location: "Rooftop Lounge",
    type: "Networking",
    tags: ["Networking", "Social", "Industry"],
    attendees: 150,
    organizer: "Networking Committee",
    venue: "Rooftop Lounge",
    venueAddress: "555 Sky Tower, Business District, City 12345",
    ticketPrice: "$25 (includes appetizers)",
    dresscode: "Business Casual",
    agenda: [
      "7:00 PM - Welcome Reception",
      "7:30 PM - Speed Networking Sessions",
      "8:30 PM - Open Networking",
      "9:30 PM - Closing Remarks",
    ],
    speakers: ["Industry Leaders Panel"],
    requirements: "RSVP required",
    contact: "networking@directorsguild.org",
  },
]

export function getEventById(id: string): Event | undefined {
  return eventsData.find((event) => event.id === id)
}
