// Gallery data - separate from main API file
import type { GalleryMedia } from "./types"

export interface GalleryEvent {
  id: string
  name: string
  description: string
  date: string
  media: GalleryMedia[] // Changed from images to media
}

export const galleryEvents: GalleryEvent[] = [
  {
    id: "annual-awards-2023",
    name: "Annual Awards Ceremony 2023",
    description: "Our prestigious annual awards ceremony celebrating excellence in directing",
    date: "Dec 15, 2023",
    media: [
      {
        id: "awards-1",
        title: "Opening Ceremony",
        description: "Grand opening of the annual awards ceremony with industry leaders.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Events",
        date: "Dec 15, 2023",
        tags: ["awards", "ceremony", "opening"],
      },
      {
        id: "awards-2",
        title: "Best Director Award Announcement",
        description: "The moment when the Best Director award was announced - full ceremony video.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Video+Thumbnail",
        type: "video",
        category: "Events",
        date: "Dec 15, 2023",
        duration: "15:30",
        tags: ["awards", "ceremony", "best director", "video"],
      },
      {
        id: "awards-3",
        title: "Red Carpet Arrivals",
        description: "Directors arriving at the red carpet for the awards ceremony.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Events",
        date: "Dec 15, 2023",
        tags: ["awards", "red carpet", "arrivals"],
      },
      {
        id: "awards-4",
        title: "Lifetime Achievement Award Ceremony",
        description: "Complete video of the lifetime achievement award presentation.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Lifetime+Achievement+Video",
        type: "video",
        category: "Events",
        date: "Dec 15, 2023",
        duration: "12:45",
        tags: ["awards", "lifetime achievement", "honor", "video"],
      },
      {
        id: "awards-5",
        title: "Winners Group Photo",
        description: "All award winners posing together after the ceremony.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Events",
        date: "Dec 15, 2023",
        tags: ["awards", "winners", "group photo"],
      },
      {
        id: "awards-6",
        title: "Acceptance Speech Highlights",
        description: "Compilation of the most emotional acceptance speeches from the evening.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Speech+Highlights",
        type: "video",
        category: "Events",
        date: "Dec 15, 2023",
        duration: "8:20",
        tags: ["awards", "speech", "emotional", "video"],
      },
      {
        id: "awards-7",
        title: "Industry Networking",
        description: "Directors networking during the awards ceremony reception.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Events",
        date: "Dec 15, 2023",
        tags: ["awards", "networking", "reception"],
      },
      {
        id: "awards-8",
        title: "Closing Ceremony",
        description: "The grand finale of the awards ceremony with fireworks.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Events",
        date: "Dec 15, 2023",
        tags: ["awards", "closing", "fireworks"],
      },
    ],
  },
  {
    id: "summer-workshop-2023",
    name: "Summer Workshop Series 2023",
    description: "Intensive workshops on advanced cinematography and directing techniques",
    date: "Jul 22, 2023",
    media: [
      {
        id: "workshop-1",
        title: "Cinematography Masterclass",
        description: "Hands-on cinematography techniques being demonstrated by experts.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Workshops",
        date: "Jul 22, 2023",
        tags: ["workshop", "cinematography", "masterclass"],
      },
      {
        id: "workshop-2",
        title: "Camera Equipment Demo Video",
        description: "Complete demonstration of latest camera equipment for participants.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Equipment+Demo",
        type: "video",
        category: "Workshops",
        date: "Jul 22, 2023",
        duration: "25:15",
        tags: ["workshop", "equipment", "demo", "video"],
      },
      {
        id: "workshop-3",
        title: "Student Presentations",
        description: "Workshop participants presenting their creative projects.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Workshops",
        date: "Jul 22, 2023",
        tags: ["workshop", "students", "presentations"],
      },
      {
        id: "workshop-4",
        title: "Lighting Techniques Tutorial",
        description: "Professional lighting setup demonstration for film production - full tutorial.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Lighting+Tutorial",
        type: "video",
        category: "Workshops",
        date: "Jul 22, 2023",
        duration: "18:40",
        tags: ["workshop", "lighting", "techniques", "video"],
      },
      {
        id: "workshop-5",
        title: "Director's Panel",
        description: "Panel discussion with renowned directors sharing their experiences.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Workshops",
        date: "Jul 22, 2023",
        tags: ["workshop", "panel", "directors"],
      },
      {
        id: "workshop-6",
        title: "Editing Workshop Session",
        description: "Complete post-production editing techniques and software training session.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Editing+Workshop",
        type: "video",
        category: "Workshops",
        date: "Jul 22, 2023",
        duration: "32:10",
        tags: ["workshop", "editing", "post-production", "video"],
      },
    ],
  },
  {
    id: "new-directors-showcase-2023",
    name: "New Directors Showcase 2023",
    description: "Celebrating emerging talent and showcasing films by new directors",
    date: "Sep 5, 2023",
    media: [
      {
        id: "showcase-1",
        title: "Opening Night",
        description: "The grand opening of the New Directors Showcase event.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Events",
        date: "Sep 5, 2023",
        tags: ["showcase", "opening", "new directors"],
      },
      {
        id: "showcase-2",
        title: "Film Screening Highlights",
        description: "Highlights from the screening of debut films by emerging directors.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Film+Screening",
        type: "video",
        category: "Events",
        date: "Sep 5, 2023",
        duration: "22:30",
        tags: ["showcase", "screening", "debut", "video"],
      },
      {
        id: "showcase-3",
        title: "Q&A Session",
        description: "Directors answering questions from the audience after screenings.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Events",
        date: "Sep 5, 2023",
        tags: ["showcase", "q&a", "audience"],
      },
      {
        id: "showcase-4",
        title: "Emerging Talent Panel Discussion",
        description: "Full panel discussion with emerging directors sharing their journey.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Panel+Discussion",
        type: "video",
        category: "Events",
        date: "Sep 5, 2023",
        duration: "45:20",
        tags: ["showcase", "panel", "emerging talent", "video"],
      },
      {
        id: "showcase-5",
        title: "Networking Reception",
        description: "New directors networking with industry professionals.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Events",
        date: "Sep 5, 2023",
        tags: ["showcase", "networking", "reception"],
      },
    ],
  },
  {
    id: "film-production-bts-2023",
    name: "Behind the Scenes: The Last Light",
    description: "Exclusive behind-the-scenes coverage from the production of 'The Last Light'",
    date: "Nov 3, 2023",
    media: [
      {
        id: "bts-1",
        title: "Director at Work",
        description: "Director Sarah Johnson directing a crucial scene during night shoot.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Behind the Scenes",
        date: "Nov 3, 2023",
        tags: ["production", "director", "night shoot"],
      },
      {
        id: "bts-2",
        title: "Complete Night Shoot Footage",
        description: "Full behind-the-scenes footage of the night shoot including setup and multiple takes.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Night+Shoot+BTS",
        type: "video",
        category: "Behind the Scenes",
        date: "Nov 3, 2023",
        duration: "28:45",
        tags: ["production", "night shoot", "bts", "video"],
      },
      {
        id: "bts-3",
        title: "Cast Rehearsal",
        description: "Actors rehearsing their lines before the actual take.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Behind the Scenes",
        date: "Nov 3, 2023",
        tags: ["production", "cast", "rehearsal"],
      },
      {
        id: "bts-4",
        title: "Director's Commentary",
        description: "Director Sarah Johnson provides commentary on the filmmaking process.",
        url: "/placeholder.svg?height=600&width=800&text=Video+Placeholder",
        thumbnailUrl: "/placeholder.svg?height=600&width=800&text=Director+Commentary",
        type: "video",
        category: "Behind the Scenes",
        date: "Nov 3, 2023",
        duration: "15:30",
        tags: ["production", "director", "commentary", "video"],
      },
      {
        id: "bts-5",
        title: "Wrap Party",
        description: "Cast and crew celebrating the successful completion of filming.",
        url: "/placeholder.svg?height=600&width=800",
        type: "image",
        category: "Behind the Scenes",
        date: "Nov 3, 2023",
        tags: ["production", "wrap party", "celebration"],
      },
    ],
  },
]

// Function to get all media (for backward compatibility)
export function getAllGalleryImages(): GalleryMedia[] {
  return galleryEvents.flatMap((event) => event.media)
}

// Function to get events with their media
export function getGalleryEvents(): GalleryEvent[] {
  return galleryEvents
}
