import type { Member } from "./types"

export const foundingMembers: Member[] = [
  {
    id: "founding-1",
    name: "William Wyler",
    specialty: "Drama",
    bio: "Three-time Academy Award winner and founding member of the Directors Guild. Known for Ben-Hur, The Best Years of Our Lives, and Roman Holiday.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Classic Hollywood", "Academy Winner", "Guild Founder"],
    email: "",
    phone: "",
    location: "Los Angeles, CA",
  },
  {
    id: "founding-2",
    name: "John Ford",
    specialty: "Western",
    bio: "Legendary director and guild founding member who defined the Western genre. Four-time Oscar winner known for The Searchers and Stagecoach.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Western Master", "Four-time Oscar Winner", "Guild Founder"],
    email: "",
    phone: "",
    location: "Monument Valley, UT",
  },
  {
    id: "founding-3",
    name: "Frank Capra",
    specialty: "Drama",
    bio: "First president of the Directors Guild and master of American populist cinema. Known for It's a Wonderful Life and Mr. Smith Goes to Washington.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Guild President", "Populist Cinema", "American Classic"],
    email: "",
    phone: "",
    location: "Los Angeles, CA",
  },
  {
    id: "founding-4",
    name: "George Stevens",
    specialty: "Drama",
    bio: "Guild founding member and two-time Oscar winner. Directed Giant, Shane, and A Place in the Sun with masterful storytelling.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Two-time Oscar Winner", "Epic Drama", "Guild Founder"],
    email: "",
    phone: "",
    location: "Los Angeles, CA",
  },
  {
    id: "founding-5",
    name: "Leo McCarey",
    specialty: "Comedy",
    bio: "Founding member known for screwball comedies and drama. Directed The Awful Truth, Going My Way, and Duck Soup with the Marx Brothers.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Screwball Comedy", "Marx Brothers", "Guild Founder"],
    email: "",
    phone: "",
    location: "Los Angeles, CA",
  },
  {
    id: "founding-6",
    name: "King Vidor",
    specialty: "Drama",
    bio: "Pioneering director and guild founding member. Known for The Big Parade, The Crowd, and innovative silent film techniques.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Silent Film Pioneer", "Social Drama", "Guild Founder"],
    email: "",
    phone: "",
    location: "Los Angeles, CA",
  },
]

export const deceasedMembers: Member[] = [
  {
    id: "deceased-1",
    name: "Robert Altman",
    specialty: "Drama",
    bio: "Legendary director known for his innovative ensemble films and overlapping dialogue technique. His masterpieces include Nashville, MASH, and The Player.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Ensemble Films", "Independent Cinema", "Innovative Storytelling"],
    email: "",
    phone: "",
    location: "Los Angeles, CA",
  },
  {
    id: "deceased-2",
    name: "Sidney Lumet",
    specialty: "Drama",
    bio: "Master of character-driven dramas who directed classics like 12 Angry Men, Serpico, and Network. Known for his work with actors and social themes.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Character Drama", "Social Commentary", "Actor's Director"],
    email: "",
    phone: "",
    location: "New York, NY",
  },
  {
    id: "deceased-3",
    name: "John Hughes",
    specialty: "Comedy",
    bio: "Beloved filmmaker who defined teen cinema in the 1980s with films like The Breakfast Club, Ferris Bueller's Day Off, and Sixteen Candles.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Teen Comedy", "Coming of Age", "80s Cinema"],
    email: "",
    phone: "",
    location: "Chicago, IL",
  },
  {
    id: "deceased-4",
    name: "Hal Ashby",
    specialty: "Drama",
    bio: "Counterculture filmmaker known for Harold and Maude, Being There, and Coming Home. Master of dark comedy and social satire.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Counterculture", "Dark Comedy", "Social Satire"],
    email: "",
    phone: "",
    location: "Los Angeles, CA",
  },
  {
    id: "deceased-5",
    name: "George Romero",
    specialty: "Horror",
    bio: "Pioneer of zombie horror films who created Night of the Living Dead and revolutionized the horror genre with social commentary.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Horror", "Zombie Films", "Independent Cinema"],
    email: "",
    phone: "",
    location: "Pittsburgh, PA",
  },
  {
    id: "deceased-6",
    name: "Penny Marshall",
    specialty: "Comedy",
    bio: "Groundbreaking female director who helmed Big, A League of Their Own, and Awakenings. First woman to direct a film grossing over $100 million.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Comedy", "Sports Films", "Female Pioneer"],
    email: "",
    phone: "",
    location: "Los Angeles, CA",
  },
]

export const lifetimeMembers: Member[] = [
  {
    id: "lifetime-1",
    name: "Martin Scorsese",
    specialty: "Drama",
    bio: "Legendary filmmaker and cinema preservationist known for Goodfellas, Taxi Driver, and The Departed. Master of crime dramas and character studies.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Crime Drama", "Character Study", "Cinema History"],
    email: "m.scorsese@guild.com",
    phone: "(555) 001-0001",
    location: "New York, NY",
  },
  {
    id: "lifetime-2",
    name: "Steven Spielberg",
    specialty: "Adventure",
    bio: "Iconic director of blockbusters and intimate dramas including Jaws, E.T., Schindler's List, and Saving Private Ryan. Pioneer of modern cinema.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Blockbuster", "Historical Drama", "Adventure"],
    email: "s.spielberg@guild.com",
    phone: "(555) 001-0002",
    location: "Los Angeles, CA",
  },
  {
    id: "lifetime-3",
    name: "Francis Ford Coppola",
    specialty: "Drama",
    bio: "Visionary director of The Godfather trilogy, Apocalypse Now, and The Conversation. Pioneer of New Hollywood and independent filmmaking.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Epic Drama", "New Hollywood", "Independent Cinema"],
    email: "f.coppola@guild.com",
    phone: "(555) 001-0003",
    location: "San Francisco, CA",
  },
  {
    id: "lifetime-4",
    name: "Ridley Scott",
    specialty: "Sci-Fi",
    bio: "Master of visual storytelling known for Alien, Blade Runner, Gladiator, and The Martian. Expert in science fiction and historical epics.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Science Fiction", "Visual Effects", "Historical Epic"],
    email: "r.scott@guild.com",
    phone: "(555) 001-0004",
    location: "London, UK",
  },
  {
    id: "lifetime-5",
    name: "Barbra Streisand",
    specialty: "Drama",
    bio: "Multi-talented artist who directed Yentl, The Prince of Tides, and The Mirror Has Two Faces. Pioneer for women directors in Hollywood.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Drama", "Musical", "Female Director"],
    email: "b.streisand@guild.com",
    phone: "(555) 001-0005",
    location: "Malibu, CA",
  },
  {
    id: "lifetime-6",
    name: "Woody Allen",
    specialty: "Comedy",
    bio: "Prolific filmmaker known for Annie Hall, Manhattan, and Midnight in Paris. Master of neurotic comedy and romantic dramas.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Romantic Comedy", "Neurotic Humor", "New York Stories"],
    email: "w.allen@guild.com",
    phone: "(555) 001-0006",
    location: "New York, NY",
  },
  {
    id: "lifetime-7",
    name: "George Lucas",
    specialty: "Sci-Fi",
    bio: "Creator of Star Wars and Indiana Jones franchises. Revolutionary in special effects and digital filmmaking technology.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Science Fiction", "Special Effects", "Franchise Builder"],
    email: "g.lucas@guild.com",
    phone: "(555) 001-0007",
    location: "San Rafael, CA",
  },
]

export const fullMembers: Member[] = [
  {
    id: "full-1",
    name: "Ava DuVernay",
    specialty: "Drama",
    bio: "Acclaimed director of Selma, 13th, and When They See Us. Champion of social justice storytelling and diverse representation in cinema.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Social Justice", "Historical Drama", "Documentary"],
    email: "a.duvernay@guild.com",
    phone: "(555) 005-0001",
    location: "Los Angeles, CA",
  },
  {
    id: "full-2",
    name: "Taika Waititi",
    specialty: "Comedy",
    bio: "New Zealand filmmaker known for Thor: Ragnarok, Jojo Rabbit, and Hunt for the Wilderpeople. Master of quirky humor and heartfelt storytelling.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Quirky Comedy", "Heartfelt Stories", "Marvel"],
    email: "t.waititi@guild.com",
    phone: "(555) 005-0002",
    location: "Auckland, New Zealand",
  },
  {
    id: "full-3",
    name: "Bong Joon-ho",
    specialty: "Thriller",
    bio: "Oscar-winning director of Parasite, Okja, and The Host. Master of genre-blending social commentary and dark humor.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Social Commentary", "Genre-Blending", "Korean Cinema"],
    email: "b.joonho@guild.com",
    phone: "(555) 005-0003",
    location: "Seoul, South Korea",
  },
  {
    id: "full-4",
    name: "Patty Jenkins",
    specialty: "Action",
    bio: "Director of Wonder Woman and Monster. Pioneer for female directors in superhero cinema and character-driven action films.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Superhero Films", "Female Director", "Character Action"],
    email: "p.jenkins@guild.com",
    phone: "(555) 005-0004",
    location: "Los Angeles, CA",
  },
  {
    id: "full-5",
    name: "Damien Chazelle",
    specialty: "Musical",
    bio: "Youngest Best Director Oscar winner for La La Land. Also directed Whiplash and First Man. Expert in music-driven storytelling.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Musical Drama", "Young Talent", "Music-Driven"],
    email: "d.chazelle@guild.com",
    phone: "(555) 005-0005",
    location: "Los Angeles, CA",
  },
  {
    id: "full-6",
    name: "Céline Sciamma",
    specialty: "Drama",
    bio: "French director of Portrait of a Lady on Fire and Girlhood. Master of intimate character studies and female perspectives.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Intimate Drama", "Female Perspective", "French Cinema"],
    email: "c.sciamma@guild.com",
    phone: "(555) 005-0006",
    location: "Paris, France",
  },
  {
    id: "full-7",
    name: "Robert Eggers",
    specialty: "Horror",
    bio: "Visionary horror director of The Witch, The Lighthouse, and The Northman. Master of period authenticity and atmospheric terror.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Period Horror", "Atmospheric", "Historical Accuracy"],
    email: "r.eggers@guild.com",
    phone: "(555) 005-0007",
    location: "New York, NY",
  },
  {
    id: "full-8",
    name: "Lulu Wang",
    specialty: "Drama",
    bio: "Acclaimed director of The Farewell. Expert in cross-cultural storytelling and family dramas.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Cross-Cultural", "Family Drama", "Independent Cinema"],
    email: "l.wang@guild.com",
    phone: "(555) 005-0008",
    location: "New York, NY",
  },
  {
    id: "full-9",
    name: "Destin Daniel Cretton",
    specialty: "Drama",
    bio: "Director of Shang-Chi and the Legend of the Ten Rings, Short Term 12, and The Glass Castle. Expert in character-driven narratives.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Character Drama", "Marvel", "Independent Spirit"],
    email: "d.cretton@guild.com",
    phone: "(555) 005-0009",
    location: "Los Angeles, CA",
  },
  {
    id: "full-10",
    name: "Chloé Zhao",
    specialty: "Drama",
    bio: "Oscar-winning director of Nomadland and The Rider. Expert in naturalistic storytelling and non-professional actors.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Naturalistic Drama", "Non-Professional Actors", "Landscape Cinema"],
    email: "c.zhao@guild.com",
    phone: "(555) 005-0010",
    location: "Los Angeles, CA",
  },
]

export const currentExecutiveCommittee: Member[] = [
  {
    id: "exec-current-1",
    name: "Christopher Nolan",
    specialty: "Sci-Fi",
    bio: "President - Visionary director known for complex narratives in Inception, Interstellar, and The Dark Knight trilogy. Master of practical effects.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Complex Narratives", "Practical Effects", "IMAX"],
    email: "c.nolan@guild.com",
    phone: "(555) 002-0001",
    location: "Los Angeles, CA",
  },
  {
    id: "exec-current-2",
    name: "Greta Gerwig",
    specialty: "Comedy",
    bio: "Vice President - Acclaimed director of Lady Bird and Little Women. Champion of female voices in cinema and coming-of-age storytelling.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Coming of Age", "Female Perspective", "Independent Cinema"],
    email: "g.gerwig@guild.com",
    phone: "(555) 002-0002",
    location: "New York, NY",
  },
  {
    id: "exec-current-3",
    name: "Jordan Peele",
    specialty: "Horror",
    bio: "Secretary - Innovative horror director of Get Out, Us, and Nope. Master of social commentary through genre filmmaking.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Social Horror", "Genre Innovation", "Cultural Commentary"],
    email: "j.peele@guild.com",
    phone: "(555) 002-0003",
    location: "Los Angeles, CA",
  },
  {
    id: "exec-current-4",
    name: "Denis Villeneuve",
    specialty: "Sci-Fi",
    bio: "Treasurer - Visionary sci-fi director of Arrival, Blade Runner 2049, and Dune. Master of atmospheric storytelling.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Atmospheric Cinema", "Science Fiction", "Visual Poetry"],
    email: "d.villeneuve@guild.com",
    phone: "(555) 002-0004",
    location: "Montreal, Canada",
  },
  {
    id: "exec-current-5",
    name: "Ryan Coogler",
    specialty: "Action",
    bio: "Board Member - Dynamic director of Black Panther, Creed, and Fruitvale Station. Champion of diverse storytelling in blockbuster cinema.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Superhero Films", "Diverse Storytelling", "Action Drama"],
    email: "r.coogler@guild.com",
    phone: "(555) 002-0006",
    location: "Oakland, CA",
  },
  {
    id: "exec-current-6",
    name: "Ari Aster",
    specialty: "Horror",
    bio: "Board Member - Innovative horror auteur known for Hereditary and Midsommar. Master of psychological terror and visual composition.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Psychological Horror", "Visual Composition", "Art House Horror"],
    email: "a.aster@guild.com",
    phone: "(555) 002-0007",
    location: "New York, NY",
  },
  {
    id: "exec-current-7",
    name: "Barry Jenkins",
    specialty: "Drama",
    bio: "Board Member - Oscar-winning director of Moonlight and If Beale Street Could Talk. Master of intimate character studies.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Character Study", "LGBTQ+ Cinema", "Intimate Drama"],
    email: "b.jenkins@guild.com",
    phone: "(555) 002-0009",
    location: "Los Angeles, CA",
  },
  {
    id: "exec-current-8",
    name: "Emerald Fennell",
    specialty: "Thriller",
    bio: "Board Member - Bold director of Promising Young Woman. Expert in genre-bending feminist narratives.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Feminist Cinema", "Genre-Bending", "Social Thriller"],
    email: "e.fennell@guild.com",
    phone: "(555) 002-0010",
    location: "London, UK",
  },
]

export const previousExecutiveCommittee: Member[] = [
  {
    id: "exec-previous-1",
    name: "Kathryn Bigelow",
    specialty: "Action",
    bio: "Former President - First woman to win Best Director Oscar for The Hurt Locker. Master of intense action and war films.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["War Films", "Action", "Female Pioneer"],
    email: "k.bigelow@guild.com",
    phone: "(555) 003-0001",
    location: "Los Angeles, CA",
  },
  {
    id: "exec-previous-2",
    name: "Quentin Tarantino",
    specialty: "Crime",
    bio: "Former Vice President - Iconic filmmaker known for Pulp Fiction, Kill Bill, and Django Unchained. Master of dialogue and genre homage.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Crime Films", "Genre Homage", "Dialogue Master"],
    email: "q.tarantino@guild.com",
    phone: "(555) 003-0002",
    location: "Los Angeles, CA",
  },
  {
    id: "exec-previous-3",
    name: "Paul Thomas Anderson",
    specialty: "Drama",
    bio: "Former Secretary - Auteur director of There Will Be Blood, Phantom Thread, and Boogie Nights. Master of character-driven epics.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Character Epic", "Auteur Cinema", "Period Drama"],
    email: "p.anderson@guild.com",
    phone: "(555) 003-0003",
    location: "Los Angeles, CA",
  },
  {
    id: "exec-previous-4",
    name: "Sofia Coppola",
    specialty: "Drama",
    bio: "Former Treasurer - Distinctive filmmaker known for Lost in Translation, Marie Antoinette, and The Virgin Suicides. Master of mood and atmosphere.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Atmospheric Drama", "Female Perspective", "Visual Poetry"],
    email: "s.coppola@guild.com",
    phone: "(555) 003-0004",
    location: "New York, NY",
  },
  {
    id: "exec-previous-5",
    name: "David Fincher",
    specialty: "Thriller",
    bio: "Former Board Member - Meticulous director of Fight Club, Se7en, and The Social Network. Master of dark psychological thrillers.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Psychological Thriller", "Dark Cinema", "Technical Precision"],
    email: "d.fincher@guild.com",
    phone: "(555) 003-0005",
    location: "San Francisco, CA",
  },
  {
    id: "exec-previous-6",
    name: "Wes Anderson",
    specialty: "Comedy",
    bio: "Former Board Member - Distinctive visual stylist known for The Grand Budapest Hotel, Moonrise Kingdom, and The Royal Tenenbaums.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Visual Style", "Quirky Comedy", "Symmetrical Composition"],
    email: "w.anderson@guild.com",
    phone: "(555) 003-0006",
    location: "New York, NY",
  },
  {
    id: "exec-previous-7",
    name: "Guillermo del Toro",
    specialty: "Fantasy",
    bio: "Former Board Member - Visionary fantasy director of Pan's Labyrinth, The Shape of Water, and Hellboy. Master of creature design.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Fantasy", "Creature Design", "Dark Fairy Tales"],
    email: "g.deltoro@guild.com",
    phone: "(555) 003-0007",
    location: "Los Angeles, CA",
  },
  {
    id: "exec-previous-8",
    name: "Spike Lee",
    specialty: "Drama",
    bio: "Former Board Member - Pioneering filmmaker of Do the Right Thing, Malcolm X, and BlacKkKlansman. Master of social commentary.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Social Commentary", "African American Cinema", "Political Drama"],
    email: "s.lee@guild.com",
    phone: "(555) 003-0008",
    location: "Brooklyn, NY",
  },
  {
    id: "exec-previous-9",
    name: "Coen Brothers",
    specialty: "Crime",
    bio: "Former Board Members - Joel and Ethan Coen, masters of dark comedy and crime films including Fargo, No Country for Old Men.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Dark Comedy", "Crime Films", "Collaborative Direction"],
    email: "coen.brothers@guild.com",
    phone: "(555) 003-0009",
    location: "New York, NY",
  },
  {
    id: "exec-previous-10",
    name: "Alejandro G. Iñárritu",
    specialty: "Drama",
    bio: "Former Board Member - Acclaimed director of Birdman, The Revenant, and Babel. Master of complex narrative structures.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Complex Narratives", "Long Takes", "International Cinema"],
    email: "a.inarritu@guild.com",
    phone: "(555) 003-0010",
    location: "Mexico City, Mexico",
  },
]

export const generalMembers: Member[] = [
  {
    id: "general-1",
    name: "Sarah Chen",
    specialty: "Documentary",
    bio: "Award-winning documentary filmmaker specializing in environmental and social justice issues. Her latest work explores climate change impact on coastal communities.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Environmental", "Social Justice", "Climate Change"],
    email: "s.chen@guild.com",
    phone: "(555) 004-0001",
    location: "San Francisco, CA",
  },
  {
    id: "general-2",
    name: "Marcus Rodriguez",
    specialty: "Action",
    bio: "Rising action director known for innovative stunt choreography and practical effects. Currently developing a superhero project with diverse casting.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Stunt Choreography", "Practical Effects", "Superhero"],
    email: "m.rodriguez@guild.com",
    phone: "(555) 004-0002",
    location: "Atlanta, GA",
  },
  {
    id: "general-3",
    name: "Emily Watson",
    specialty: "Romance",
    bio: "Romantic comedy specialist with a fresh take on modern relationships. Her films blend humor with authentic emotional depth.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Romantic Comedy", "Modern Relationships", "Authentic Emotion"],
    email: "e.watson@guild.com",
    phone: "(555) 004-0003",
    location: "Nashville, TN",
  },
  {
    id: "general-4",
    name: "David Kim",
    specialty: "Animation",
    bio: "Innovative animation director pushing the boundaries of 3D and mixed-media storytelling. Expert in both traditional and digital techniques.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["3D Animation", "Mixed Media", "Digital Innovation"],
    email: "d.kim@guild.com",
    phone: "(555) 004-0004",
    location: "Portland, OR",
  },
  {
    id: "general-5",
    name: "Isabella Rossi",
    specialty: "Musical",
    bio: "Musical theater director transitioning to film. Known for elaborate choreography and bringing Broadway energy to the big screen.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Musical Theater", "Choreography", "Broadway"],
    email: "i.rossi@guild.com",
    phone: "(555) 004-0005",
    location: "New York, NY",
  },
  {
    id: "general-6",
    name: "James Thompson",
    specialty: "Western",
    bio: "Modern western filmmaker bringing contemporary themes to classic genre conventions. Expert in landscape cinematography and period authenticity.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Modern Western", "Landscape", "Period Authenticity"],
    email: "j.thompson@guild.com",
    phone: "(555) 004-0006",
    location: "Austin, TX",
  },
  {
    id: "general-7",
    name: "Priya Patel",
    specialty: "Drama",
    bio: "Independent drama director focusing on immigrant experiences and cultural identity. Her films have won multiple festival awards.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Immigrant Stories", "Cultural Identity", "Festival Circuit"],
    email: "p.patel@guild.com",
    phone: "(555) 004-0007",
    location: "Chicago, IL",
  },
  {
    id: "general-8",
    name: "Robert Mitchell",
    specialty: "Noir",
    bio: "Neo-noir specialist bringing classic film noir aesthetics to modern storytelling. Master of shadow, light, and moral ambiguity.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Neo-Noir", "Classic Aesthetics", "Moral Ambiguity"],
    email: "r.mitchell@guild.com",
    phone: "(555) 004-0008",
    location: "Los Angeles, CA",
  },
  {
    id: "general-9",
    name: "Lisa Chang",
    specialty: "Sci-Fi",
    bio: "Science fiction director specializing in near-future scenarios and technology's impact on humanity. Known for thought-provoking narratives.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Near Future", "Technology", "Thought Provoking"],
    email: "l.chang@guild.com",
    phone: "(555) 004-0009",
    location: "Seattle, WA",
  },
  {
    id: "general-10",
    name: "Antonio Silva",
    specialty: "Sports",
    bio: "Sports drama director with background in professional athletics. Brings authentic sports knowledge to compelling human stories.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Sports Drama", "Athletic Background", "Human Stories"],
    email: "a.silva@guild.com",
    phone: "(555) 004-0010",
    location: "Miami, FL",
  },
  {
    id: "general-11",
    name: "Rachel Green",
    specialty: "Comedy",
    bio: "Sketch comedy veteran transitioning to feature films. Known for ensemble casts and improvisational directing techniques.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Sketch Comedy", "Ensemble Cast", "Improvisation"],
    email: "r.green@guild.com",
    phone: "(555) 004-0011",
    location: "Los Angeles, CA",
  },
  {
    id: "general-12",
    name: "Michael O'Brien",
    specialty: "War",
    bio: "Military veteran turned filmmaker specializing in authentic war stories. Consultant on military accuracy for major studios.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Military Veteran", "Authentic War Stories", "Military Consultant"],
    email: "m.obrien@guild.com",
    phone: "(555) 004-0012",
    location: "Washington, DC",
  },
  {
    id: "general-13",
    name: "Yuki Tanaka",
    specialty: "Horror",
    bio: "J-horror influenced director bringing Eastern horror sensibilities to Western audiences. Expert in psychological terror and supernatural themes.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["J-Horror", "Psychological Terror", "Supernatural"],
    email: "y.tanaka@guild.com",
    phone: "(555) 004-0013",
    location: "Los Angeles, CA",
  },
  {
    id: "general-14",
    name: "Hannah Schmidt",
    specialty: "Biopic",
    bio: "Biographical film specialist known for meticulous research and compelling character portrayals. Expert in historical period recreation.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Biographical Films", "Historical Research", "Character Portrayal"],
    email: "h.schmidt@guild.com",
    phone: "(555) 004-0014",
    location: "Boston, MA",
  },
  {
    id: "general-15",
    name: "Carlos Mendoza",
    specialty: "Family",
    bio: "Family entertainment director creating wholesome content that appeals to all ages. Expert in balancing humor with meaningful messages.",
    image: "/placeholder.svg?height=300&width=300",
    tags: ["Family Entertainment", "All Ages", "Meaningful Messages"],
    email: "c.mendoza@guild.com",
    phone: "(555) 004-0015",
    location: "Orlando, FL",
  },
]

// Helper function to get all members
export const getAllMembers = (): Member[] => {
  return [
    ...foundingMembers,
    ...deceasedMembers,
    ...lifetimeMembers,
    ...fullMembers,
    ...currentExecutiveCommittee,
    ...previousExecutiveCommittee,
    ...generalMembers,
  ]
}

// Function to fetch a member by ID
export async function fetchMemberById(id: string): Promise<Member | null> {
  // Search through all member categories
  const allMembers = getAllMembers()
  const member = allMembers.find((m) => m.id === id)

  if (!member) {
    return null
  }

  // For deceased members, we need to handle them differently
  const isDeceased = deceasedMembers.some((m) => m.id === id)

  // Enhance the member object with additional details for the detail page
  const enhancedMember = {
    ...member,
    coverImage: "/placeholder.svg?height=600&width=1200&text=Director+Profile",
    website: member.website || (isDeceased ? "" : "https://example.com/portfolio"),
    socialLinks:
      member.socialLinks ||
      (isDeceased
        ? {}
        : {
            twitter: "https://twitter.com/example",
            instagram: "https://instagram.com/example",
            linkedin: "https://linkedin.com/in/example",
          }),
    filmography: member.filmography || [
      {
        title: isDeceased ? "Night of the Living Dead" : "The Director's Vision",
        year: isDeceased ? "1968" : "2023",
        role: "Director",
      },
      {
        title: isDeceased ? "Dawn of the Dead" : "Creative Horizons",
        year: isDeceased ? "1978" : "2021",
        role: "Director/Writer",
      },
      {
        title: isDeceased ? "Day of the Dead" : "Cinematic Journey",
        year: isDeceased ? "1985" : "2019",
        role: "Director",
      },
    ],
    awards: member.awards || [
      {
        title: isDeceased ? "Lifetime Achievement Award" : "Best Director",
        organization: isDeceased ? "Horror Film Association" : "Independent Film Festival",
        year: isDeceased ? "1999" : "2022",
      },
      {
        title: isDeceased ? "Pioneer of Horror" : "Outstanding Achievement",
        organization: isDeceased ? "Genre Film Society" : "Film Critics Association",
        year: isDeceased ? "1995" : "2020",
      },
    ],
    showreelUrl: member.showreelUrl || "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    showreelThumbnail: member.showreelThumbnail || "/placeholder.svg?height=720&width=1280&text=Director+Showreel",
  }

  return enhancedMember as Member
}
